---
title: "triple_diff"
author: "Claire Morton"
date: "2026-06-19"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggpubr)
library(fixest)
library(mvtnorm)
library(patchwork)
library(readr)
library(tidyverse)
library(patchwork)
```

```{r}
aggregate_data <- function(data, 
                           cols_to_keep, 
                           pop_col,
                           agg_noneuca = TRUE){
  
  pop_cols <- c("pop_ACS", "pop_MPI")
  
  data_pop <- data %>% 
    select(-setdiff(pop_cols, pop_col)) %>%
    rename("pop" = !!sym(pop_col))
  
  raw_pop <- data_pop %>%
    group_by(state, region) %>%
    summarize(pop = first(pop), .groups = "drop")
  
  # find geographic keys
  geo_keys <- intersect(cols_to_keep, c("state", "region"))
  
  # aggregate regions if requested
  if(agg_noneuca){
    data_pop <- data_pop %>% 
      mutate(region = ifelse(region == "EUCA", "EUCA", "nonEUCA")) %>%
      group_by(pick(-c(n_arrests, pop))) %>%
      summarize(n_arrests = sum(n_arrests)/n(),
                pop = sum(pop))
    
    raw_pop <- raw_pop %>% 
      mutate(region = ifelse(region == "EUCA", "EUCA", "nonEUCA")) %>%
      group_by(state, region) %>%
      summarize(pop = sum(pop), .groups = "drop")
  }
  # population map
  pop_map <- data_pop %>%
    group_by(state, region, pop) %>%
    slice_head(n = 1) %>%
    ungroup() %>%
    group_by_at(geo_keys) %>%
    summarize(pop = sum(pop), .groups = "drop")
  
   # checksum value
  checksum <- data_pop %>%
    group_by(state, region, pop) %>%
    slice_head(n=1) %>%
    ungroup() %>%
    group_by(region) %>%
    summarize(pop_checksum = sum(pop), .groups = "drop")

  # aggregate arrests, join population back in
  data_pop <- data_pop %>%
    group_by_at(cols_to_keep) %>%
    summarize(n_arrests = sum(n_arrests, na.rm = TRUE), .groups = "drop") %>%
    left_join(pop_map, by = geo_keys) %>%
    mutate(ratio = n_arrests/pop*1000,
           log_pop = log(pop))
  
  # checksum
  total_aggregated <- data_pop %>%
    ungroup() %>%
    group_by_at(geo_keys) %>%
    summarize(pop = first(pop), .groups = "drop") %>%
    pull(pop) %>%
    sum(na.rm = TRUE)
  
  total_checksum <- sum(checksum$pop_checksum, na.rm = TRUE)
  
  if (!(dplyr::near(total_checksum, total_aggregated))) {
    warning("Checksum Failed!")
  }
  
  return(data_pop)
}

```

```{r, echo = F}
trajectory <- read_csv("../data/processed/glm_trajectory_type_threatlevel_convicted_ACS_MPI.csv") 
sum(trajectory$n_arrests)

trajectory <- trajectory %>%
  mutate(conv_method = ifelse(method == "LEA", 
                              ifelse(convicted == 1, "LEA_conv", "LEA_nonconv"),
                              ifelse(method == "CA", 
                                     ifelse(convicted == 1, "CA_conv", "CA_nonconv"),
                                     NA)))

trajectory <- trajectory %>%
  filter(method == "CA") %>%
  select(state, region, window, conv_method, n_arrests, pop_MPI)

conv_method_state <- trajectory %>%
  filter(window >= -1) %>%
  mutate(window = ifelse(window >= 0, 0, -1)) %>%
  group_by(region, state, window, conv_method) %>%
  summarize(pop_MPI = mean(pop_MPI),
            n_arrests = mean(n_arrests)) %>%
  mutate(region = ifelse(region == "EUCA", "EUCA", "nonEUCA")) %>%
  group_by(region, state, window, conv_method) %>%
  summarize(pop_MPI = sum(pop_MPI), 
            n_arrests = sum(n_arrests)) %>%
  group_by(window, region, state, conv_method, pop_MPI) %>%
  summarize(n_arrests = sum(n_arrests),
            ratio = sum(n_arrests)/sum(pop_MPI)*1000) 

wt_fml <- as.formula("~ pop_MPI")
model_fml <- as.formula(
  paste0("ratio ~ i(window, region, ref = -1, ref2 = 'EUCA') | region + window")
)

return_p_value <- function(data){
  states <- unique(data$state)
  n_states <- length(states)
  
  coef_nonconv <- coef(feols(model_fml, data %>% filter(conv_method == "CA_nonconv"), weights = wt_fml, cluster = ~state)) 
  coef_conv <- coef(feols(model_fml, data %>% filter(conv_method == "CA_conv"), weights = wt_fml, cluster = ~state))
  mean = unname(coef_nonconv - coef_conv)
  jackknife_est_matrix <- t(sapply(states, function(dropped_state) {
    sub_data <- subset(data, state != dropped_state)
    coef_nonconv <- coef(feols(model_fml, sub_data %>% filter(conv_method == "CA_nonconv"), weights = wt_fml, cluster = ~state)) 
    coef_conv <- coef(feols(model_fml, sub_data %>% filter(conv_method == "CA_conv"), weights = wt_fml, cluster = ~state))
    coef_nonconv - coef_conv
  }))
  
  var = sum((jackknife_est_matrix - mean)^2)*(n_states-1)/(n_states)
  se = sqrt(var)
  z = mean/se
  print(pnorm(-abs(z))*2)
  print(c(mean, mean - 1.96*se, mean + 1.96*se))
}

return_p_value(conv_method_state)
```

```{r, echo = F}
trajectory <- read_csv("../data/processed/glm_trajectory_type_threatlevel_convicted_ACS_MPI.csv") 
sum(trajectory$n_arrests)

trajectory <- trajectory %>%
  mutate(conv_method = ifelse(method == "LEA", 
                              ifelse(convicted == 1, "LEA_conv", "LEA_nonconv"),
                              ifelse(method == "CA", 
                                     ifelse(convicted == 1, "CA_conv", "CA_nonconv"),
                                     NA)))

trajectory <- trajectory %>%
  filter(method == "LEA") %>%
  select(state, region, window, conv_method, n_arrests, pop_MPI)

conv_method_state <- trajectory %>%
  filter(window >= -1) %>%
  mutate(window = ifelse(window >= 0, 0, -1)) %>%
  group_by(region, state, window, conv_method) %>%
  summarize(pop_MPI = mean(pop_MPI),
            n_arrests = mean(n_arrests)) %>%
  mutate(region = ifelse(region == "EUCA", "EUCA", "nonEUCA")) %>%
  group_by(region, state, window, conv_method) %>%
  summarize(pop_MPI = sum(pop_MPI), 
            n_arrests = sum(n_arrests)) %>%
  group_by(window, region, state, conv_method, pop_MPI) %>%
  summarize(n_arrests = sum(n_arrests),
            ratio = sum(n_arrests)/sum(pop_MPI)*1000) 
  
wt_fml <- as.formula("~ pop_MPI")
model_fml <- as.formula(
  paste0("ratio ~ i(window, region, ref = -1, ref2 = 'EUCA') | region + window")
)

return_p_value <- function(data){
  states <- unique(data$state)
  n_states <- length(states)
  
  coef_nonconv <- coef(feols(model_fml, data %>% filter(conv_method == "LEA_nonconv"), weights = wt_fml, cluster = ~state)) 
  coef_conv <- coef(feols(model_fml, data %>% filter(conv_method == "LEA_conv"), weights = wt_fml, cluster = ~state))
  mean = unname(coef_nonconv - coef_conv)
  
  jackknife_est_matrix <- t(sapply(states, function(dropped_state) {
    sub_data <- subset(data, state != dropped_state)
    coef_nonconv <- coef(feols(model_fml, sub_data %>% filter(conv_method == "LEA_nonconv"), weights = wt_fml, cluster = ~state)) 
    coef_conv <- coef(feols(model_fml, sub_data %>% filter(conv_method == "LEA_conv"), weights = wt_fml, cluster = ~state))
    coef_nonconv - coef_conv
  }))
  
  var = sum((jackknife_est_matrix - mean)^2)*(n_states-1)/(n_states)
  se = sqrt(var)
  z = mean/se
  print(pnorm(-abs(z))*2)
  print(c(mean, mean - 1.96*se, mean + 1.96*se))
}

return_p_value(conv_method_state)
```

```{r}

```