---
title: "make_Table_1"
author: "Claire Morton"
date: "2026-06-18"
output: pdf_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
```

```{r}
trajectory <- read_csv("../data/glm_trajectory_type_threatlevel_convicted_ACS_MPI.csv")

n_arrests_pre <-trajectory %>%
  filter(window < 0) %>%
  group_by(region) %>%
  summarize(n_arrests_pre = sum(n_arrests))

n_arrests_post <- trajectory %>%
  filter(window >= 0) %>%
  group_by(region) %>%
  summarize(n_arrests_post = sum(n_arrests))

pop_MPI <- trajectory %>%
  filter(window == 0 & method == "CA" & alt_method == "CA" & convicted == 0 & threat_level == 0) %>%
  group_by(region) %>%
  summarize(pop_MPI = sum(pop_MPI))

tab <- merge(merge(n_arrests_pre, n_arrests_post), pop_MPI) %>%
  mutate(per_1k_pre = n_arrests_pre/pop_MPI*1000,
         per_1k_post = n_arrests_post/pop_MPI*1000) %>%
  arrange(-pop_MPI)

tab_EUCA <- tab %>%
  filter(region == "EUCA")
tab_nonEUCA <- tab %>%
  filter(region != "EUCA")
tab_totals <- data.frame(t(colSums(tab_nonEUCA[-1]))) %>%
  mutate(per_1k_pre = n_arrests_pre/pop_MPI*1000,
         per_1k_post = n_arrests_post/pop_MPI*1000)
tab_totals$region = "All Non-EUCA"

tab_totals_all <- data.frame(t(colSums(tab[-1]))) %>%
  mutate(per_1k_pre = n_arrests_pre/pop_MPI*1000,
         per_1k_post = n_arrests_post/pop_MPI*1000)
tab_totals_all$region = "All"

rbind(tab_EUCA, tab_nonEUCA, tab_totals, tab_totals_all) %>%
  mutate(per_1k_pre = round(per_1k_pre, 1),
         per_1k_post = round(per_1k_post, 1))
```